#!/usr/bin/env bash

set -eu -o pipefail

# ------------------------------------------------------------------------------
# Global variables
# ------------------------------------------------------------------------------
PROGRAM="${0##*/}"
OPENAI_MODEL="${OPENAI_MODEL:-gpt-3.5-turbo-16k}"
BASHGPT_DEBUG="${BASHGPT_DEBUG:-false}"
BASHGPT_HOME="${BASHGPT_HOME:-$HOME/.bashgpt}"

# ------------------------------------------------------------------------------
# Functions
# ------------------------------------------------------------------------------
# shellcheck disable=SC2120
usage() {
  local exit_code="${1:-0}"

  gum format -- << EOL
_usage: $PROGRAM [OPTIONS]_

# Options
  * --help                show help information

# Commands:

## Assistant
  * create-assistant      create a new assistant
  * delete-assistant      delete an assistant
  * list-assistants       list assistants

## Threads
  * start-thread          start a new thread
  * delete-thread         delete a thread
  * get-thread            get a thread

## Messages
  * add-message           add a message to a thread
  * list-messages         list messages in a thread

## Runs
  * run-thread            starts running a thread
  * list-runs             list runs for a thread
  * get-run               get a thread's run
  * cancel-run            cancel a thread's run
  * list-steps            list steps for a thread's run
  * get-step              get a thread's run step

_Each command has its own set of options. Run '$PROGRAM COMMAND --help' for
more information._

# Environmental variables

  * OPENAI_API_KEY        your OpenAI API key (required; create one at https://beta.openai.com/account/api-keys)
  * OPENAI_MODEL          the model to use; defaults to gpt-3.5-turbo-16k
  * BASHGPT_HOME          the directory to store the model and other files; defaults to ~/.bashgpt

# See also
  * [API docs](https://platform.openai.com/docs/api-reference/assistants)

EOL

  exit "$exit_code"
}

info() {
  gum style --foreground="#00FF00" "$PROGRAM: $*" >&2
}

warn() {
  local msg="${1:-something went wrong}"
  gum style --foreground="#FF0000" "$PROGRAM: $msg" >&2
}

die() {
  warn "$@"
  exit 1
}

validate-env() {
  local tools=("curl" "jq" "awk" "sort" "sha256sum" "tee")
  local cmd

  for cmd in "${tools[@]}"; do
    if ! command -v "$cmd" &> /dev/null; then
      die "$cmd is not installed"
    fi
  done

  if [ -z "${OPENAI_API_KEY:-}" ]; then
    die "OPENAI_API_KEY is not set in the environment"
  elif [[ ! "$OPENAI_API_KEY" =~ ^sk-[a-zA-Z0-9]{32,64}$ ]]; then
    die "OPENAI_API_KEY is not a valid key"
  fi

  mkdir -p "$BASHGPT_HOME"

  return 0
}

# ------------------------------------------------------------------------------
# if get-flag --flag "$@"; then
#   ...
# fi
# ------------------------------------------------------------------------------
get-flag() {
  local flag="$1"

  for param in "${@:2}"; do
    if [[ "$param" == "$flag" ]]; then
      return 0
    fi
  done

  return 1
}

# ------------------------------------------------------------------------------
# flag_value=$(get-config --flag "$@") || die "missing --flag"
# ------------------------------------------------------------------------------
get-config() {
  local name="$1"
  local capture=false
  local param

  for param in "${@:2}"; do
    if [[ "$capture" == true ]]; then
      echo "$param"
      return 0
    elif [[ "$param" == "$name" ]]; then
      capture=true
    fi
  done

  return 1
}

# ------------------------------------------------------------------------------
# declare -a flag_values
# get-config-multi --flag flag_values "$@" || die "missing --flag"
# ------------------------------------------------------------------------------
get-config-multi() {
  local name="$1"
  local -n return_var="$2"
  local param
  local capture_next=false

  return_var=() # Clear the array to store results

  for param in "${@:3}"; do
    if [[ "$capture_next" == true ]]; then
      return_var+=("$param")
      capture_next=false
      continue
    fi

    if [[ "$param" == "$name" ]]; then
      capture_next=true
    elif [[ "$param" =~ ^$name=.+ ]]; then
      return_var+=("${param#*=}")
    fi
  done

  [[ ${#return_var[@]} -eq 0 ]] && return 1
}

request() {
  local response
  response=$(curl -s "$@") || die "API connection error"
  response-ok "$response"
  echo "$response"
}

response-ok() {
  if jq -e 'has("error")' <<< "$1" > /dev/null; then
    die "$(echo "$1" | jq -r '.error.message')"
  fi

  return 0
}

cmd:list-assistants() {
  if get-flag --help "$@"; then
    cat << EOL
usage: $PROGRAM list-assistants

options:
  --help            show help information
EOL

    exit 0
  fi

  request "https://api.openai.com/v1/assistants?order=desc&limit=20" \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer $OPENAI_API_KEY" \
    -H "OpenAI-Beta: assistants=v1"
}

cmd:delete-assistant() {
  local id

  if get-flag --help "$@"; then
    cat << EOL
usage: $PROGRAM delete-assistant [OPTIONS]

options:
  --help            show help information
  --id              the id of the assistant (required)
EOL

    exit 0
  fi

  id=$(get-config --id "$@") || die "delete-assistant: expected --id"

  request "https://api.openai.com/v1/assistants/$id" \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer $OPENAI_API_KEY" \
    -H "OpenAI-Beta: assistants=v1" \
    -X DELETE
}

cmd:create-assistant() {
  local name
  local instructions
  local description
  local payload

  if get-flag --help "$@"; then
    cat << EOL
usage: $PROGRAM create-assistant [OPTIONS]

options:
  --help            show help information
  --name            the name of the assistant (required)
  --instructions    the instructions for the assistant (required)
  --description     the description of the assistant
EOL

    exit 0
  fi

  name=$(get-config --name "$@") || die "create_assistant: expected --name"
  instructions=$(get-config --instructions "$@") || die "create_assistant: expected --instructions"
  description=$(get-config --description "$@") || true

  info "Creating assistant: $name"
  info "Instructions:       $instructions"
  info "Description:        $description"
  info "Model:              $OPENAI_MODEL"

  payload=$(jq -n '{}')
  payload=$(jq --arg x "$OPENAI_MODEL" '. + {"model": $x}' <<< "$payload")
  payload=$(jq --arg x "$name" '. + {"name": $x}' <<< "$payload")
  payload=$(jq --arg x "$instructions" '. + {"instructions": $x}' <<< "$payload")

  if [ -n "$description" ]; then
    payload=$(jq --arg x "$description" '. + {"description": $x}' <<< "$payload")
  fi

  request "https://api.openai.com/v1/assistants" \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer $OPENAI_API_KEY" \
    -H "OpenAI-Beta: assistants=v1" \
    -d "$payload"
}

cmd:start-thread() {
  local label

  if get-flag --help "$@"; then
    cat << EOL
usage: $PROGRAM start-thread [OPTIONS]

options:
  --help            show help information
  --label           the label of the thread (required)
EOL

    exit 0
  fi

  label=$(get-config --label "$@") || die "start_thread: expected --label"

  payload=$(jq -n '{}')
  payload=$(jq --arg x "$label" '. + {"metadata": {"label": $x}}' <<< "$payload")

  request https://api.openai.com/v1/threads \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer $OPENAI_API_KEY" \
    -H "OpenAI-Beta: assistants=v1" \
    -d "$payload"
}

cmd:delete-thread() {
  local thread

  if get-flag --help "$@"; then
    cat << EOL
usage: $PROGRAM delete-thread [OPTIONS]

options:
  --help            show help information
  --thread          the id of the thread (required)
EOL

    exit 0
  fi

  thread=$(get-config --thread "$@") || die "delete-assistant: expected --thread"

  request "https://api.openai.com/v1/threads/$thread" \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer $OPENAI_API_KEY" \
    -H "OpenAI-Beta: assistants=v1" \
    -X DELETE
}

cmd:get-thread() {
  local thread

  if get-flag --help "$@"; then
    cat << EOL
usage: $PROGRAM get-thread [OPTIONS]

options:
  --help            show help information
  --thread          the id of the thread (required)
EOL

    exit 0
  fi

  thread=$(get-config --thread "$@") || die "delete-assistant: expected --thread"

  request "https://api.openai.com/v1/threads/$thread" \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer $OPENAI_API_KEY" \
    -H "OpenAI-Beta: assistants=v1"
}

cmd:add-message() {
  local thread
  local message

  if get-flag --help "$@"; then
    cat << EOL
usage: $PROGRAM add-message [OPTIONS]

options:
  --help            show help information
  --thread          the id of the thread (required)
  --message         the message to add (required)
EOL

    exit 0
  fi

  thread=$(get-config --thread "$@") || die "add-message: expected --thread"
  message=$(get-config --message "$@") || die "add-message: expected --message"

  payload=$(jq -n '{"role": "user"}')
  payload=$(jq --arg x "$message" '. + {"content": $x}' <<< "$payload")

  request "https://api.openai.com/v1/threads/$thread/messages" \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer $OPENAI_API_KEY" \
    -H "OpenAI-Beta: assistants=v1" \
    -d "$payload"
}

cmd:list-messages() {
  local thread

  if get-flag --help "$@"; then
    cat << EOL
usage: $PROGRAM list-messages [OPTIONS]

options:
  --help            show help information
  --thread          the id of the thread (required)
EOL

    exit 0
  fi

  thread=$(get-config --thread "$@") || die "add-message: expected --thread"

  request "https://api.openai.com/v1/threads/$thread/messages" \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer $OPENAI_API_KEY" \
    -H "OpenAI-Beta: assistants=v1"
}

cmd:run-thread() {
  local assistant
  local thread

  if get-flag --help "$@"; then
    cat << EOL
usage: $PROGRAM run-thread [OPTIONS]

options:
  --help            show help information
  --assistant       the id of the assistant (required)
  --thread          the id of the thread (required)
EOL

    exit 0
  fi

  assistant=$(get-config --assistant "$@") || die "run-thread: expected --assistant"
  thread=$(get-config --thread "$@") || die "run-thread: expected --thread"

  request "https://api.openai.com/v1/threads/$thread/runs" \
    -H "Authorization: Bearer $OPENAI_API_KEY" \
    -H 'Content-Type: application/json' \
    -H 'OpenAI-Beta: assistants=v1' \
    -d "{\"assistant_id\": \"$assistant\"}"
}

cmd:list-runs() {
  local thread

  if get-flag --help "$@"; then
    cat << EOL
usage: $PROGRAM list-runs [OPTIONS]

options:
  --help            show help information
  --thread          the id of the thread (required)
EOL

    exit 0
  fi

  thread=$(get-config --thread "$@") || die "list-runs: expected --thread"

  request "https://api.openai.com/v1/threads/$thread/runs" \
    -H "Authorization: Bearer $OPENAI_API_KEY" \
    -H 'Content-Type: application/json' \
    -H 'OpenAI-Beta: assistants=v1'
}

cmd:get-run() {
  local thread
  local run

  if get-flag --help "$@"; then
    cat << EOL
usage: $PROGRAM get-run [OPTIONS]

options:
  --help            show help information
  --thread          the id of the thread (required)
  --run             the id of the run (required)
EOL

    exit 0
  fi

  thread=$(get-config --thread "$@") || die "get-run: expected --thread"
  run=$(get-config --run "$@") || die "get-run: expected --run"

  request "https://api.openai.com/v1/threads/$thread/runs/$run" \
    -H "Authorization: Bearer $OPENAI_API_KEY" \
    -H 'OpenAI-Beta: assistants=v1'
}

cmd:cancel-run() {
  local thread
  local run

  if get-flag --help "$@"; then
    cat << EOL
usage: $PROGRAM cancel-run [OPTIONS]

options:
  --help            show help information
  --thread          the id of the thread (required)
  --run             the id of the run (required)
EOL

    exit 0
  fi

  thread=$(get-config --thread "$@") || die "cancel-run: expected --thread"
  run=$(get-config --run "$@") || die "cancel-run: expected --run"

  request "https://api.openai.com/v1/threads/$thread/runs/$run/cancel" \
    -H "Authorization: Bearer $OPENAI_API_KEY" \
    -H 'OpenAI-Beta: assistants=v1' \
    -X POST
}

cmd:list-steps() {
  local thread
  local run

  if get-flag --help "$@"; then
    cat << EOL
usage: $PROGRAM list-steps [OPTIONS]

options:
  --help            show help information
  --thread          the id of the thread (required)
  --run             the id of the run (required)
EOL

    exit 0
  fi

  thread=$(get-config --thread "$@") || die "list-steps: expected --thread"
  run=$(get-config --run "$@") || die "list-steps: expected --run"

  request "https://api.openai.com/v1/threads/$thread/runs/$run/steps" \
    -H "Authorization: Bearer $OPENAI_API_KEY" \
    -H 'Content-Type: application/json' \
    -H 'OpenAI-Beta: assistants=v1'
}

cmd:get-step() {
  local thread
  local run
  local step

  if get-flag --help "$@"; then
    cat << EOL
usage: $PROGRAM get-step [OPTIONS]

options:
  --help            show help information
  --thread          the id of the thread (required)
  --run             the id of the run (required)
  --step            the id of the step (required)
EOL

    exit 0
  fi

  thread=$(get-config --thread "$@") || die "cancel-run: expected --thread"
  run=$(get-config --run "$@") || die "cancel-run: expected --run"
  step=$(get-config --step "$@") || die "cancel-run: expected --step"

  request "https://api.openai.com/v1/threads/$thread/runs/$run/steps/$step" \
    -H "Authorization: Bearer $OPENAI_API_KEY" \
    -H 'Content-Type: application/json' \
    -H 'OpenAI-Beta: assistants=v1'
}

main() {
  local options

  validate-env

  if [ "$#" -eq 0 ]; then
    usage 1
  fi

  options=$(declare -F | grep '^declare -f cmd:' | cut -d ' ' -f 3)

  for option in $options; do
    flag=${option#cmd:}

    if get-flag "$flag" "$@"; then
      "$option" "${@:2}"
      exit 0
    fi
  done

  if get-flag --help "$@"; then
    usage 0
  fi
}

main "$@"
